#This is a sample yaml file for the KKE Devops task deploy-GB-app
#Edit the below lines as per your question.
#Anything in between <> braket need to be replaced by the details from your questions.
#Check this blog https://thirigiri.blogspot.com for kubenetes commands, how to deply this file and complete the task.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: back-end
  template:
    metadata:
      labels:
        app: guestbook
        tier: back-end
    spec:
      containers:
        - name: master-redis-xfusion 
          image: <image name/URL from question>
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"  
          ports:
            - containerPort: 6379
