#This is a sample yaml file for the KKE Devops task deploy-GB-app
#Edit the below lines as per your question.
#Anything in between <> braket need to be replaced by the details from your questions.
#Check this blog https://thirigiri.blogspot.com for kubenetes commands, how to deply this file and complete the task.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deployment-name-from-question>
spec:
  replicas: <from-question>
  selector:
    matchLabels:
      app: <from-question>
      tier: back-end
  template:
    metadata:
      labels:
        app: <from-question>
        tier: back-end
    spec:
      containers:
        - name: <container-name-from-question> 
          image: <image name/URL from question>
          resources:
            requests:
              cpu: "<from-question>"
              memory: "<from-question>"  
          ports:
            - containerPort: <conainer-port-from-question>
