


apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
spec:
  volumes:
  - name: volume-share
    emptyDir: {}

  containers:

  - name: volume-container-datacenter-1
    image: centos:latest
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/beta
    command: ['/bin/bash','-c','sleep 10000']
	
  - name: volume-container-datacenter-2
    image: centos:latest
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/apps
    command: ['/bin/bash','-c','sleep 10000']
