#This is a sample yaml file for the KKE Devops task Kubernetes share volumes.
#Edit the below codes as per your details from your questions.
#Check this blog https://thirigiri.blogspot.com for how to deply this file, complete the task and kubenetes commands.

apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
spec:
  volumes:
  - name: volume-share
    emptyDir: {}

  containers:

  - name: volume-container-datacenter-1
    image: centos:latest
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/beta
    command: ['/bin/bash','-c','sleep 10000']
	
  - name: volume-container-datacenter-2
    image: centos:latest
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/apps
    command: ['/bin/bash','-c','sleep 10000']
